angular.module('sbAdminApp')
    .controller('privilegeController',['$scope', function($scope) {
        //alert("haha");
        $scope.roles=[
            {
                "roleid":1001,
                "rolename":"rolename1",
                "privileges":[{
                    "privilegeid":1001,
                    "privilegename":"privilegename11",
                    "url":"/xxxx1"
                },{
                    "privilegeid":1002,
                    "privilegename":"privilegename12",
                    "url":"/xxxx1"
                },{
                    "privilegeid":1003,
                    "privilegename":"privilegename13",
                    "url":"/xxxx1"
                }]
            },
            {
                "roleid":1002,
                "rolename":"rolename2",
                "privileges":[{
                    "privilegeid":2001,
                    "privilegename":"privilegename21",
                    "url":"/xxxx1"
                },{
                    "privilegeid":2002,
                    "privilegename":"privilegename22",
                    "url":"/xxxx1"
                },{
                    "privilegeid":2003,
                    "privilegename":"privilegename23",
                    "url":"/xxxx1"
                }]
            },
            {
                "roleid":1003,
                "rolename":"rolename3",
                "privileges":[{
                    "privilegeid":3001,
                    "privilegename":"privilegename31",
                    "url":"/xxxx1"
                },{
                    "privilegeid":3002,
                    "privilegename":"privilegename32",
                    "url":"/xxxx1"
                },{
                    "privilegeid":3003,
                    "privilegename":"privilegename33",
                    "url":"/xxxx1"
                }]
            },
            {
                "roleid":1004,
                "rolename":"rolename4",
                "privileges":[{
                    "privilegeid":4001,
                    "privilegename":"privilegename41",
                    "url":"/xxxx1"
                },{
                    "privilegeid":4002,
                    "privilegename":"privilegename42",
                    "url":"/xxxx1"
                },{
                    "privilegeid":4003,
                    "privilegename":"privilegename43",
                    "url":"/xxxx1"
                }]
            }
        ];

        $scope.createTenant = function(tenant){
            alert(tenant.tenantname);
        }

        $scope.privileges=[{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"

        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"

        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"

        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"

        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"
        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"
        },{
            "privilegeid":1001,
            "privilegename":"privilegename11",
            "url":"/xxxx1"
        }]
    }]);